swagger: "2.0"
info:
  description: "This is a simple test API"
  version: "1.0.0"
  title: "Swagger School"
host: "pure-castle-01571.herokuapp.com"
basePath: "/v1"
tags:
- name: "school"
  description: "Simple school crud"
schemes:
- "https"
paths:
  /schools/:
    get:
      tags:
      - "school"
      summary: "List all schools"
      description: ""
      operationId: "get"
      produces:
      - "application/json"
      responses:
        "405":
          description: "Invalid input"
  
    post:
      tags:
      - "school"
      summary: "Add a new school"
      description: ""
      operationId: "post"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "School object that needs to be added"
        required: true
        schema:
          $ref: "#/definitions/School"
      responses:
        "405":
          description: "Invalid input"
    put:
      tags:
      - "school"
      summary: "Update an existing School"
      description: ""
      operationId: "put"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "School object that needs to be updated"
        required: true
        schema:
          $ref: "#/definitions/School"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "School not found"
        "405":
          description: "Validation exception"
  /schools/{id}:
    get:
      tags:
      - "school"
      summary: "Find School by ID"
      description: "Returns a single school"
      operationId: "getById"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "ID of school to return"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/School"
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "Schoolnot found"
    delete:
      tags:
      - "school"
      summary: "Deletes a school"
      description: ""
      operationId: "delete"
      produces:
      - "application/json"
      parameters:
      - name: "id"
        in: "path"
        description: "School id to delete"
        required: true
        type: "integer"
        format: "int64"
      responses:
        "400":
          description: "Invalid ID supplied"
        "404":
          description: "School not found"
definitions:
  School:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
        description: "School name"
      email:
        type: "string"
        description: "School name"
  ApiResponse:
    type: "object"
    properties:
      code:
        type: "integer"
        format: "int32"
      type:
        type: "string"
      message:
        type: "string"